apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-test8
  labels:
    app: api-d-test8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-test8
  template:
    metadata:
      labels:
        app: api-test8
    spec:
      containers:
        - name: api-container-test8
          image: rodrigodocker123/mtprueba:82
          ports:
            - containerPort: 5000    