apiVersion: v1
kind: Service
metadata:
#  namespace: eks-test
  name: mysql-external-service-1
spec:
  type: NodePort
  selector: # no debe apuntar al label del deploy, debe ser al del pod definido en el deploy
    app:  mysql-ubuntu-1
  ports:
   - protocol: TCP
     port: 3307
     targetPort: 3306
     nodePort: 30037
