apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-test2
  labels:
    app: api-d-test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-test2
  template:
    metadata:
      labels:
        app: api-test2
    spec:
      containers:
        - name: api-container-test2
          image: rodrigodocker123/mtprueba:2
          ports:
            - containerPort: 5000    