apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-7
  labels:
    app: api-d-7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-7
  template:
    metadata:
      labels:
        app: api-7
    spec:
      containers:
        - name: api-container7
          image: rodrigodocker123/mtbackend2:7
          ports:
            - containerPort: 5000    