apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-8
  labels:
    app: api-d-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-8
  template:
    metadata:
      labels:
        app: api-8
    spec:
      containers:
        - name: api-container8
          image: rodrigodocker123/mtbackend2:8
          ports:
            - containerPort: 5000    