apiVersion: apps/v1
kind: Deployment
metadata: # cosas del deployment object
  name: mysql-ubuntu-deployment-1
  labels:
    app: mysql-ubuntu-d-1
spec: 
  replicas: 1 # define la cantidad de pods que se necesitan corriendo -> 
  selector:
    matchLabels: # aca le estamos diciendo de que agarre todo los pods con esa label
      app: mysql-ubuntu-1
  template: #aca se estan definiendo como van a ser los pods -> estado deseado
    metadata: 
      labels:
        app: mysql-ubuntu-1
    spec:
      containers: 
        - name: mysql-ubuntu-container
          image: rodrigodocker123/mtdatabase
          ports:
            - containerPort: 3306