apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-9
  labels:
    app: api-d-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-9
  template:
    metadata:
      labels:
        app: api-9
    spec:
      containers:
        - name: api-container9
          image: rodrigodocker123/mtbackend2:9
          ports:
            - containerPort: 5000    