apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-test3
  labels:
    app: api-d-test3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-test3
  template:
    metadata:
      labels:
        app: api-test3
    spec:
      containers:
        - name: api-container-test3
          image: rodrigodocker123/mtprueba:3
          ports:
            - containerPort: 5000    