apiVersion: v1
kind: Service
metadata:
  name: front-api-test-service
spec:
  type: NodePort
  selector:
    app: api-1
    app: api-2
    app: api-3
    app: api-4
    app: api-5
    app: api-6
    app: api-7
    app: api-8
    app: api-9
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5000
      nodePort: 32767