apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-test7
  labels:
    app: api-d-test7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-test7
  template:
    metadata:
      labels:
        app: api-test7
    spec:
      containers:
        - name: api-container-test7
          image: rodrigodocker123/mtprueba:7
          ports:
            - containerPort: 5000    